services:
  - type: web
    name: mediai-backend
    env: docker
    plan: free
    region: singapore

    buildCommand: ""
    startCommand: ""

    envVars:
      - key: PORT
        value: 8080

      - key: DB_HOST
        fromDatabase:
          name: MediSageAI
          property: host

      - key: DB_PORT
        fromDatabase:
          name: MediSageAI
          property: port

      - key: DB_NAME
        fromDatabase:
          name: MediSageAI
          property: database

      - key: DB_USER
        fromDatabase:
          name: MediSageAI
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: MediSageAI
          property: password

      - key: JWT_SECRET
        generateValue: true

      - key: GROQ_API_KEY
        sync: false

      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: MediSageAI
    plan: free
    region: singapore
